package templates

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"text/template"
)

// TemplateInfo represents metadata about a template
type TemplateInfo struct {
	Name        string `json:"name"`
	Category    string `json:"category"`
	Description string `json:"description"`
	Content     string `json:"content,omitempty"`
}

// Engine manages Go text/templates for document assembly
type Engine struct {
	mu        sync.RWMutex
	templates map[string]*TemplateInfo
	dir       string
}

// NewEngine creates a new template engine and loads built-in templates
func NewEngine(dir string) *Engine {
	e := &Engine{
		templates: make(map[string]*TemplateInfo),
		dir:       dir,
	}
	e.loadBuiltIn()
	e.loadFromDir(dir)
	return e
}

// loadBuiltIn registers the built-in templates
func (e *Engine) loadBuiltIn() {
	builtIn := []TemplateInfo{
		{
			Name:        "executive-summary",
			Category:    "business",
			Description: "Executive summary report with title, summary, analysis, and recommendations",
			Content: `# {{.Title}}

## Executive Summary
{{.Summary}}

## Analysis
{{.Analysis}}

## Key Findings
{{.Findings}}

## Recommendations
{{.Recommendations}}

---
*Generated by TAS Assembler*
`,
		},
		{
			Name:        "technical-report",
			Category:    "technical",
			Description: "Technical report with overview, methodology, results, and conclusion",
			Content: `# {{.Title}}

## Overview
{{.Overview}}

## Methodology
{{.Methodology}}

## Results
{{.Results}}

## Technical Details
{{.Details}}

## Conclusion
{{.Conclusion}}

---
*Generated by TAS Assembler*
`,
		},
		{
			Name:        "meeting-notes",
			Category:    "business",
			Description: "Meeting notes with attendees, agenda, discussion, and action items",
			Content: `# Meeting Notes: {{.Title}}

**Date:** {{.Date}}
**Attendees:** {{.Attendees}}

## Agenda
{{.Agenda}}

## Discussion
{{.Discussion}}

## Decisions
{{.Decisions}}

## Action Items
{{.ActionItems}}

---
*Generated by TAS Assembler*
`,
		},
		{
			Name:        "compliance-report",
			Category:    "compliance",
			Description: "Compliance audit report with findings, risk assessment, and remediation",
			Content: `# Compliance Report: {{.Title}}

**Date:** {{.Date}}
**Auditor:** {{.Auditor}}
**Scope:** {{.Scope}}

## Executive Summary
{{.Summary}}

## Findings
{{.Findings}}

## Risk Assessment
{{.RiskAssessment}}

## Remediation Steps
{{.Remediation}}

## Compliance Score
{{.Score}}

---
*Generated by TAS Assembler*
`,
		},
	}

	for i := range builtIn {
		e.templates[builtIn[i].Name] = &builtIn[i]
	}
}

// loadFromDir loads .tmpl files from the templates directory
func (e *Engine) loadFromDir(dir string) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return // Dir may not exist yet
	}

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".tmpl") {
			continue
		}
		content, err := os.ReadFile(filepath.Join(dir, entry.Name()))
		if err != nil {
			continue
		}
		name := strings.TrimSuffix(entry.Name(), ".tmpl")
		if _, exists := e.templates[name]; !exists {
			e.templates[name] = &TemplateInfo{
				Name:        name,
				Category:    "custom",
				Description: fmt.Sprintf("Custom template: %s", name),
				Content:     string(content),
			}
		}
	}
}

// Get returns a template by name
func (e *Engine) Get(name string) (*TemplateInfo, error) {
	e.mu.RLock()
	defer e.mu.RUnlock()

	tmpl, ok := e.templates[name]
	if !ok {
		return nil, fmt.Errorf("template '%s' not found", name)
	}
	return tmpl, nil
}

// List returns all templates, optionally filtered by category
func (e *Engine) List(category string) []TemplateInfo {
	e.mu.RLock()
	defer e.mu.RUnlock()

	var result []TemplateInfo
	for _, tmpl := range e.templates {
		if category == "" || tmpl.Category == category {
			result = append(result, TemplateInfo{
				Name:        tmpl.Name,
				Category:    tmpl.Category,
				Description: tmpl.Description,
			})
		}
	}
	return result
}

// Create adds a new template
func (e *Engine) Create(name, content, category, description string) error {
	e.mu.Lock()
	defer e.mu.Unlock()

	// Validate the template parses
	if _, err := template.New(name).Parse(content); err != nil {
		return fmt.Errorf("invalid template: %v", err)
	}

	if category == "" {
		category = "custom"
	}
	if description == "" {
		description = fmt.Sprintf("Custom template: %s", name)
	}

	e.templates[name] = &TemplateInfo{
		Name:        name,
		Category:    category,
		Description: description,
		Content:     content,
	}

	// Persist to disk if templates dir exists
	if e.dir != "" {
		os.MkdirAll(e.dir, 0755)
		os.WriteFile(filepath.Join(e.dir, name+".tmpl"), []byte(content), 0644)
	}

	return nil
}

// Render executes a template with the given parameters
func (e *Engine) Render(templateContent string, params map[string]interface{}) (string, error) {
	tmpl, err := template.New("doc").Parse(templateContent)
	if err != nil {
		return "", fmt.Errorf("template parse error: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, params); err != nil {
		return "", fmt.Errorf("template execution error: %v", err)
	}

	return buf.String(), nil
}

// DefaultTemplate returns a simple default template that renders all params
func DefaultTemplate() string {
	return `# Document

{{range $key, $value := .}}## {{$key}}
{{$value}}

{{end}}
---
*Generated by TAS Assembler*
`
}
