//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedFileStatus) DeepCopyInto(out *GeneratedFileStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedFileStatus.
func (in *GeneratedFileStatus) DeepCopy() *GeneratedFileStatus {
	if in == nil {
		return nil
	}
	out := new(GeneratedFileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinStorageSpec) DeepCopyInto(out *NapkinStorageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinStorageSpec.
func (in *NapkinStorageSpec) DeepCopy() *NapkinStorageSpec {
	if in == nil {
		return nil
	}
	out := new(NapkinStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinStyleSpec) DeepCopyInto(out *NapkinStyleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinStyleSpec.
func (in *NapkinStyleSpec) DeepCopy() *NapkinStyleSpec {
	if in == nil {
		return nil
	}
	out := new(NapkinStyleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinVisual) DeepCopyInto(out *NapkinVisual) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinVisual.
func (in *NapkinVisual) DeepCopy() *NapkinVisual {
	if in == nil {
		return nil
	}
	out := new(NapkinVisual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NapkinVisual) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinVisualCondition) DeepCopyInto(out *NapkinVisualCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinVisualCondition.
func (in *NapkinVisualCondition) DeepCopy() *NapkinVisualCondition {
	if in == nil {
		return nil
	}
	out := new(NapkinVisualCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinVisualList) DeepCopyInto(out *NapkinVisualList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NapkinVisual, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinVisualList.
func (in *NapkinVisualList) DeepCopy() *NapkinVisualList {
	if in == nil {
		return nil
	}
	out := new(NapkinVisualList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NapkinVisualList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinVisualSpec) DeepCopyInto(out *NapkinVisualSpec) {
	*out = *in
	out.Style = in.Style
	out.ApiKeySecretRef = in.ApiKeySecretRef
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinVisualSpec.
func (in *NapkinVisualSpec) DeepCopy() *NapkinVisualSpec {
	if in == nil {
		return nil
	}
	out := new(NapkinVisualSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NapkinVisualStatus) DeepCopyInto(out *NapkinVisualStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]NapkinVisualCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GeneratedFiles != nil {
		in, out := &in.GeneratedFiles, &out.GeneratedFiles
		*out = make([]GeneratedFileStatus, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NapkinVisualStatus.
func (in *NapkinVisualStatus) DeepCopy() *NapkinVisualStatus {
	if in == nil {
		return nil
	}
	out := new(NapkinVisualStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
